//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LocalPolicyRevised.Resources {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MessageResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MessageResources() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LocalPolicyRevised.Resources.MessageResources", typeof(MessageResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대해 현재 스레드의 CurrentUICulture 속성을
        ///   재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Unable to create new GPO instance with path &apos;{0}&apos; and display name &apos;{1}&apos;.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CreateGpoAtActiveDirectoryFailed {
            get {
                return ResourceManager.GetString("CreateGpoAtActiveDirectoryFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Error deleting the GPO.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string DeleteGpoFailed {
            get {
                return ResourceManager.GetString("DeleteGpoFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Unable to retrieve display name.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string GetDisplayNameFailed {
            get {
                return ResourceManager.GetString("GetDisplayNameFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Unable to retrieve options.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string GetOptionsFailed {
            get {
                return ResourceManager.GetString("GetOptionsFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Unable to retrieve path.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string GetPathFailed {
            get {
                return ResourceManager.GetString("GetPathFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Unable to retrieve path to section &apos;{0}&apos;.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string GetRegistryKeyPathToFailed {
            get {
                return ResourceManager.GetString("GetRegistryKeyPathToFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Unable to get section &apos;{0}&apos;.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string GetRootRegistryKeyFailed {
            get {
                return ResourceManager.GetString("GetRootRegistryKeyFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Unable to retrieve name.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string GetUniqueNameFailed {
            get {
                return ResourceManager.GetString("GetUniqueNameFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}. Error code {1} (see WinError.h)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string GroupPolicyExceptionMessage {
            get {
                return ResourceManager.GetString("GroupPolicyExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Executing assembly does not contain a GuidAttribute.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string NoGuidAttribInExecutingAssembly {
            get {
                return ResourceManager.GetString("NoGuidAttribInExecutingAssembly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Unable to open GPO at ActiveDirectory path &apos;{0}&apos;.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string OpenActiveDirectoryGpoFailed {
            get {
                return ResourceManager.GetString("OpenActiveDirectoryGpoFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Unable to open local machine GPO.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string OpenLocalMachineGpoFailed {
            get {
                return ResourceManager.GetString("OpenLocalMachineGpoFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Unable to open GPO on remote machine &apos;{0}&apos;.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string OpenRemoteMachineGpoFailed {
            get {
                return ResourceManager.GetString("OpenRemoteMachineGpoFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   This library requires use of a single-threaded apartment. Decorate your main method with the [STAThread] attribute. See http://msdn.microsoft.com/en-gb/library/windows/desktop/ms680112(v=vs.85).aspx for more documentation과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string RequiresSingleThreadedApartmentExceptionMessage {
            get {
                return ResourceManager.GetString("RequiresSingleThreadedApartmentExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Error saving machine settings.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SaveMachineSettingsFailed {
            get {
                return ResourceManager.GetString("SaveMachineSettingsFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Error saving user settings.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SaveUserSettingsFailed {
            get {
                return ResourceManager.GetString("SaveUserSettingsFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Unable set display name to {0}.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SetDisplayNameFailed {
            get {
                return ResourceManager.GetString("SetDisplayNameFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Unable to set options.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SetOptionsFailed {
            get {
                return ResourceManager.GetString("SetOptionsFailed", resourceCulture);
            }
        }
    }
}
